# Generated by Django 4.2.27 on 2026-01-27 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_number', models.CharField(blank=True, max_length=100, null=True)),
                ('expiry_date', models.DateField(blank=True, db_index=True, null=True)),
                ('manufacture_date', models.DateField(blank=True, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sell_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='business.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='products.product')),
            ],
            options={
                'verbose_name_plural': 'batches',
                'db_table': 'batches',
                'ordering': ['expiry_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qr_code', models.CharField(max_length=255)),
                ('printed_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='inventory.batch')),
                ('printed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'labels',
                'ordering': ['-printed_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('ADJUST', 'Adjustment')], max_length=10)),
                ('quantity', models.IntegerField()),
                ('reason', models.CharField(blank=True, choices=[('purchase', 'Purchase'), ('sale', 'Sale'), ('return', 'Return'), ('damage', 'Damage'), ('expired', 'Expired'), ('adjustment', 'Adjustment'), ('transfer', 'Transfer'), ('sample', 'Sample'), ('other', 'Other')], max_length=50, null=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.batch')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inventory_transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['batch', 'created_at'], name='inventory_t_batch_i_a65677_idx'), models.Index(fields=['type', 'created_at'], name='inventory_t_type_d91e72_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['product', 'expiry_date'], name='batches_product_fefee9_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['product', 'quantity'], name='batches_product_3dba62_idx'),
        ),
    ]
